---
title: Curious Workmanship
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: cw@rorani.com
description: 'Practical, visual resources for learning and applying the Gospel

'
baseurl: 
url: http://curiousworkmanship.co
twitter_username: curiouswrk
github_username: 
markdown: kramdown
